fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.14
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy (local)
        entry: uv run mypy .
        language: system
        pass_filenames: false
        types: [python]

  - repo: local
    hooks:
      - id: pytest
        name: pytest (local)
        entry: uv run pytest -v -s
        language: system
        pass_filenames: false
        types: [python]

  - repo: https://github.com/djlint/djLint
    rev: v1.39.2
    hooks:
      - id: djlint-reformat-jinja
        files: "\\.html"
        types_or: ["html"]
      - id: djlint-jinja
        files: "\\.html"
        types_or: ["html"]
